services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    pythonVersion: 3.10

startCommand: gunicorn -w 4 -b 0.0.0.0:8080 app:app
